name: Create script plugin

on:
  workflow_dispatch:
    inputs:
      plugin_name:
        description: Plugin name
        required: true
      visibility:
        description: Repo visibility
        required: true
        type: choice
        options:
          - public
          - private

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create a copy of this repo
        run: |
          echo `ls -lah`
          echo "Attempting to create repository $PLUGIN_NAME"
          gh repo create "$PLUGIN_NAME" "--$VISIBILITY" --source=. --description="This is a test"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PLUGIN_NAME: ${{ github.event.inputs.plugin_name }}
          VISIBILITY: ${{ github.event.inputs.visibility }}