name: Java CI

on:
  workflow_dispatch:
    inputs:
      plugin_name:
        description: Name of your new plugin
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test creating a repo
        run: |
          echo "$PLUGIN_NAME"
        env:
          PLUGIN_NAME: ${{ github.event.inputs.plugin_name }}