name: Create script plugin

on:
  workflow_dispatch:
    inputs:
      plugin_name:
        description: Plugin name
        required: true
      visibility:
        description: Repo visibility
        required: true
        type: choice
        options:
          - public
          - private

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create a copy of this repo
        run: |
          echo "Attempting to create repository $PLUGIN_NAME"
          git config --global init.defaultBranch main
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          rm -rf .git
          git init
          git add .
          git commit -m "Initial commit"
          gh repo create "$PLUGIN_NAME" "--$VISIBILITY" --source=. --push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PLUGIN_NAME: ${{ github.event.inputs.plugin_name }}
          VISIBILITY: ${{ github.event.inputs.visibility }}