name: Create script plugin

on:
  workflow_dispatch:
    inputs:
      plugin_name:
        description: Plugin name
        required: true
      visibility:
        description: Repo visibility
        required: true
        type: choice
        options:
          - public
          - private
      description:
        description: Plugin description (optional)
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
      - name: Create a copy of this repo
        run: |
          echo "Attempting to create repository $PLUGIN_NAME"
          git config --global init.defaultBranch main
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global url."https://${{ github.actor }}:$GITHUB_TOKEN@github.com".insteadOf "https://github.com"
          #git_config=`cat .git/config`
          #cd template
          #git init
          #echo "$git_config" > .git/config
          gh repo create "$PLUGIN_NAME" "--$VISIBILITY" --description="$DESCRIPTION" --license=MIT --clone
          cp -r template "$PLUGIN_NAME"
          cd "$PLUGIN_NAME"
          ls -lah
          git add . && git commit -m "Copy repo template"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PLUGIN_NAME: ${{ github.event.inputs.plugin_name }}
          VISIBILITY: ${{ github.event.inputs.visibility }}
          DESCRIPTION: ${{ github.event.inputs.description }}
